// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: dns.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DNSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRequest) Reset() {
	*x = DNSRequest{}
	mi := &file_dns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRequest) ProtoMessage() {}

func (x *DNSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRequest.ProtoReflect.Descriptor instead.
func (*DNSRequest) Descriptor() ([]byte, []int) {
	return file_dns_proto_rawDescGZIP(), []int{0}
}

func (x *DNSRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type DNSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSResponse) Reset() {
	*x = DNSResponse{}
	mi := &file_dns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSResponse) ProtoMessage() {}

func (x *DNSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSResponse.ProtoReflect.Descriptor instead.
func (*DNSResponse) Descriptor() ([]byte, []int) {
	return file_dns_proto_rawDescGZIP(), []int{1}
}

func (x *DNSResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DNSResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DNSListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []string               `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSListResponse) Reset() {
	*x = DNSListResponse{}
	mi := &file_dns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSListResponse) ProtoMessage() {}

func (x *DNSListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSListResponse.ProtoReflect.Descriptor instead.
func (*DNSListResponse) Descriptor() ([]byte, []int) {
	return file_dns_proto_rawDescGZIP(), []int{2}
}

func (x *DNSListResponse) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

var File_dns_proto protoreflect.FileDescriptor

const file_dns_proto_rawDesc = "" +
	"\n" +
	"\tdns.proto\x12\x06dnsmgr\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n" +
	"\n" +
	"DNSRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"7\n" +
	"\vDNSResponse\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"#\n" +
	"\x0fDNSListResponse\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips2\xb1\x01\n" +
	"\n" +
	"DNSService\x121\n" +
	"\x06AddDNS\x12\x12.dnsmgr.DNSRequest\x1a\x13.dnsmgr.DNSResponse\x124\n" +
	"\tRemoveDNS\x12\x12.dnsmgr.DNSRequest\x1a\x13.dnsmgr.DNSResponse\x12:\n" +
	"\aListDNS\x12\x16.google.protobuf.Empty\x1a\x17.dnsmgr.DNSListResponseB*Z(github.com/IliaSotnikov2005/dnsmrg/protob\x06proto3"

var (
	file_dns_proto_rawDescOnce sync.Once
	file_dns_proto_rawDescData []byte
)

func file_dns_proto_rawDescGZIP() []byte {
	file_dns_proto_rawDescOnce.Do(func() {
		file_dns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dns_proto_rawDesc), len(file_dns_proto_rawDesc)))
	})
	return file_dns_proto_rawDescData
}

var file_dns_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dns_proto_goTypes = []any{
	(*DNSRequest)(nil),      // 0: dnsmgr.DNSRequest
	(*DNSResponse)(nil),     // 1: dnsmgr.DNSResponse
	(*DNSListResponse)(nil), // 2: dnsmgr.DNSListResponse
	(*emptypb.Empty)(nil),   // 3: google.protobuf.Empty
}
var file_dns_proto_depIdxs = []int32{
	0, // 0: dnsmgr.DNSService.AddDNS:input_type -> dnsmgr.DNSRequest
	0, // 1: dnsmgr.DNSService.RemoveDNS:input_type -> dnsmgr.DNSRequest
	3, // 2: dnsmgr.DNSService.ListDNS:input_type -> google.protobuf.Empty
	1, // 3: dnsmgr.DNSService.AddDNS:output_type -> dnsmgr.DNSResponse
	1, // 4: dnsmgr.DNSService.RemoveDNS:output_type -> dnsmgr.DNSResponse
	2, // 5: dnsmgr.DNSService.ListDNS:output_type -> dnsmgr.DNSListResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dns_proto_init() }
func file_dns_proto_init() {
	if File_dns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dns_proto_rawDesc), len(file_dns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dns_proto_goTypes,
		DependencyIndexes: file_dns_proto_depIdxs,
		MessageInfos:      file_dns_proto_msgTypes,
	}.Build()
	File_dns_proto = out.File
	file_dns_proto_goTypes = nil
	file_dns_proto_depIdxs = nil
}
